spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abduyevelvin/user-registration-microservice
          search-paths:
            - "ms-config-properties/{application}/{profile}"
